@startuml

title __VALIDATOR's Class Diagram__\n

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.AdresseValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.ArticleValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.CategoryValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.ClientValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.CommandeClientValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.CommandeFournisseurValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.EntrepriseValidator {
          {static} + validate()
      }
    }
  }
  

  namespace com.GestionStock.GestionStock {
    namespace Validator {
      class com.GestionStock.GestionStock.Validator.UtilisateurValidator {
          {static} + validate()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
